---
AWSTemplateFormatVersion: 2010-09-09
Description: Create or Import S3 Bucket

Resources:

  ###########
  # Storage #
  ###########
  
  MyPersistingBucket:
    DeletionPolicy: Retain
    Type: AWS::S3::Bucket
    Properties:
      BucketName: cag-importable
      Tags:
        - Key: project
          Value: demonstration

  #########
  # Roles #
  #########

  CRUDRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: logging
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: arn:aws:logs:*:*:*
        - PolicyName: crud
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:ListBucket
                - s3:GetBucketLocation
                - s3:GetObjectVersion
                - s3:PutObject
                - s3:PutObjectAcl
                - s3:GetLifecycleConfiguration
                - s3:PutLifecycleConfiguration
                - s3:DeleteObject
              Resource: 
                Fn::Sub: ${MyPersistingBucket.Arn}/*

